### ISSUE TITLE
Unable to install profile on Device

### ISSUE THREAD

**Issue by iPhoneNinja** [project-imas/mdm-server#15]
Hi,

Thanks for the detailed explanation of steps!

All of the steps worked perfectly except the very end when I was trying to install the profile on the device. I received an error which read "The server certificate for (MY SERVER) is invalid."

Am I missing something out here? Could this be an issue with the vendor.p12 file?

Please refer the image below for more info:

![screenshot](https://cloud.githubusercontent.com/assets/8136045/3928678/7bd5b84c-240e-11e4-8c97-4791cbd2f7c1.png)

Any help would be greatly appreciated! Thanks in advance!

Best,
Adithya

**Comment by mtasic85** [comment]
This was exactly the same issue I had. So, simple solution is to follow instruction for topic 9., and once they pass step 1., then change server.cnf as you explained, and re-do topic 9.

This is related to issue #22.
