### ISSUE TITLE
Profile Installation Failed

### ISSUE THREAD

**Issue by pjfraser82** [project-imas/mdm-server#22]
I cannot seem to get the Profile to install on the devices. I think this is a certificate issue because the phone never hits up the endpoint to enrol. 

A couple of points: 

1: I have had this working on a different server. Wanted to rebuild from scratch for testing. 

2: Device gives no indicators of why the profile has failed, any idea how I can find out?

**Comment by pjfraser82** [comment]
I know my comment is vague but I am a bit unfamiliar to certificates so its hard to know what the problem is. On my old server I had a file called vendor.p12 but this one I have identity.p12 could this be something to do with it?

**Comment by pjfraser82** [comment]
seems that using the DNS name for my server was causing the issue.

**Comment by mtasic85** [comment]
I have some issue. Why would hostname cause this issue?
