### ISSUE TITLE
Missing server.crt file

### ISSUE THREAD

**Issue by ArturKeska-Xnet** [project-imas/mdm-server#26]
When running make_certs.sh it returns at the end with message: 

```
6. Copying keys and certs to server folder
mv: cannot stat `server.crt': No such file or directory 
```

It is however generated server.csr file in the foler.
Is the server.crt file the same as generated server.csr?

**Comment by ArturKeska-Xnet** [comment]
I run all commands from the server.crt script manually and after few iterations I managed to generate all keys. At the moment I have no idea what and where's the difference between script and running commands manually, so I have to assume that I did something wrong during the script execution.

**Comment by thrasr** [comment]
My guess is that an earlier step failed for some reason, causing no server.crt file to be generated.  Glad you got it working though.
