### ISSUE TITLE
Enroll.mobileconfig, Profile installation failed

### ISSUE THREAD

**Issue by ptesar-xyndata** [project-imas/mdm-server#34]
Hi, when I try to install mobileconfig on my device I get an error that the profile installation failed. How can I search for the error?

I do not have valid SSL Zert. on the server. Only the one created by the scripts. Could this be a Problem?

Thank you for answers.

**Comment by ptesar-xyndata** [comment]
Solved. There was error in mobileconfig

**Comment by SyedIsmailAhamed** [comment]
@PatrikTes Can you please advice what steps you followed while creating mobileconfig

**Comment by Aswin14** [comment]
@PatrikTes I am also facing the same issue. Can you tell me how you  overcame this issue. I used iPhone Configurator for windows for generating Enroll.mobileconfig
